[package]
name = "nakes"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.9.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "sqlite" ] }
clap = "3.0.0-beta.2"
